spring:
  application:
    name: 'kafka-demo'
  data:
    mongodb:
      database: kafka-demo
      port: 27017
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumidor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: snappy # Configura o tipo de compressão que deve ser aplicado às mensagens
      acks: 1 # Configura o acks para "all" para garantir que todas as réplicas confirmem o recebimento da mensagem
      retries: 3 # Configura o número de tentativas que o producer deve realizar para enviar a mensagem
    template:
      default-topic: test-topic
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
      driverClassName: org.h2.Driver
      password: password
      url: jdbc:h2:mem:testdb
      username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  security:
      user:
          name: sa
          password: password
server:
  port: 9081
  address: 127.0.0.1
  servlet:
    context-path: /kafka-demo
